In [5]:
import numpy as np
import torch

In [6]:
t = torch.tensor([
    [1, 2],
    [3, 4.]
])

In [7]:
t = torch.tensor([
    [1, 2],
    [3, 4]
], device='cuda:0')

In [8]:
t = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float64)

In [9]:
t = torch.arange(0, 10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [11]:
t = torch.zeros(100, 10).to('cuda:0')
print(t.shape)

torch.Size([100, 10])


In [12]:
t = torch.randn(100, 10)
print(t.shape)
print(t.size())

torch.Size([100, 10])
torch.Size([100, 10])


In [14]:
t = torch.tensor([
    [1, 2],
    [3, 4]
])
x = t.numpy()
print('type t:', type(t), 'type x:', type(x))

type t: <class 'torch.Tensor'> type x: <class 'numpy.ndarray'>


In [15]:
t = torch.tensor([
    [1, 2],
    [3, 4]
], device='cuda:0')
x = t.to('cpu').numpy()
print('type t:', type(t), 'type x:', type(x))

type t: <class 'torch.Tensor'> type x: <class 'numpy.ndarray'>


In [18]:
t = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

In [19]:
t[0, 2]

tensor(3)

In [20]:
t[:, :2]

tensor([[1, 2],
        [4, 5]])

In [21]:
t[t>3]

tensor([4, 5, 6])

In [22]:
t[0, 1] = 100
t

tensor([[  1, 100,   3],
        [  4,   5,   6]])

In [23]:
t[:, 1] = 200
t

tensor([[  1, 200,   3],
        [  4, 200,   6]])

In [24]:
t[t>10] = 20
t

tensor([[ 1, 20,  3],
        [ 4, 20,  6]])

In [25]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([0, 10, 20])
m = torch.tensor([
    [0, 1, 2],
    [100, 200, 300]
])

In [26]:
print(v + 10)
print(v ** 2)

tensor([11, 12, 13])
tensor([1, 4, 9])


In [27]:
z = v - w
u = 2 * v - w / 10 + 6.0

print(z)
print(u)

tensor([  1,  -8, -17])
tensor([ 8.,  9., 10.])


In [28]:
print(m*2.0)

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


In [29]:
print(m+v)

tensor([[  1,   3,   5],
        [101, 202, 303]])


In [30]:
print(m+m)

tensor([[  0,   2,   4],
        [200, 400, 600]])


In [31]:
X = torch.randn(100, 10)
y = X * 2 + torch.abs(X)
print(torch.mean(X))
print(X.mean())

tensor(0.0082)
tensor(0.0082)


In [33]:
X.mean().item()

0.008249220438301563

In [34]:
X.mean(0)

tensor([-0.1732,  0.0601,  0.0474, -0.1033,  0.0306,  0.0095, -0.0858,  0.2037,
         0.0458,  0.0478])

In [37]:
X.mean(1)

tensor([ 2.5522e-01,  4.5663e-01, -4.5882e-01, -2.6901e-01,  8.4234e-01,
        -7.9376e-02, -5.8501e-01,  1.4188e-01, -9.9924e-03,  1.3967e-01,
         3.4106e-01, -2.0497e-01,  1.7260e-01, -4.0975e-02,  4.8243e-01,
         1.3664e-01,  1.4158e-01, -3.8136e-01, -8.0608e-03,  1.9336e-03,
        -2.5831e-01,  4.1003e-02, -5.2233e-02,  6.5835e-01,  2.3667e-01,
        -4.6204e-01, -2.4090e-01,  3.5412e-02, -1.8751e-01, -3.3470e-01,
        -2.2289e-01, -6.3101e-01,  1.6238e-01, -6.7642e-01,  5.1867e-01,
         2.0160e-01,  1.0271e-01,  1.0465e-01,  8.7313e-02, -2.8162e-01,
        -3.9455e-03, -3.1330e-01, -4.0464e-01, -1.9002e-04,  6.2585e-01,
        -3.8445e-02, -1.5929e-01,  3.4236e-01, -1.1074e-01,  1.9515e-01,
        -3.3360e-01,  5.0554e-02, -3.1897e-01, -4.6058e-01,  9.0514e-02,
         8.1943e-02, -2.9009e-01, -2.6182e-01,  6.6588e-02,  7.4965e-01,
        -6.9804e-02, -8.7787e-02,  5.9761e-01,  5.2061e-01, -6.1697e-03,
        -2.4083e-01, -4.4620e-01, -4.5992e-01, -4.3

In [38]:
x1 = torch.tensor([
    [1, 2],
    [3, 4]
])
x2 = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

In [40]:
x1.view(4, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [41]:
x1.view(1, -1)

tensor([[1, 2, 3, 4]])

In [44]:
x2.t() # T

tensor([[10, 40],
        [20, 50],
        [30, 60]])

In [45]:
torch.cat([x1, x2], dim=1)

tensor([[ 1,  2, 10, 20, 30],
        [ 3,  4, 40, 50, 60]])

In [46]:
hwc_img_data = torch.rand(100, 64, 32, 3)
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)

In [47]:
print('hwc_img_data.shape:', hwc_img_data.shape)
print('chw_img_data.shape:', chw_img_data.shape)

hwc_img_data.shape: torch.Size([100, 64, 32, 3])
chw_img_data.shape: torch.Size([100, 3, 64, 32])


In [49]:
m = torch.randn(100, 10)
v = torch.randn(10)

In [50]:
print(torch.dot(v, v))

tensor(14.1061)


In [55]:
print(torch.mv(m, v).shape)

torch.Size([100])


In [54]:
print(torch.mm(m.t(), m).shape)

torch.Size([10, 10])


In [56]:
print(torch.mm(m, v).shape)

RuntimeError: mat2 must be a matrix

In [57]:
u, s, v = torch.svd(m)

In [61]:
# 모라게씀
print('u: ', u.shape)
print('s: ', s.shape)
print('v: ', v.shape)

u:  torch.Size([100, 10])
s:  torch.Size([10])
v:  torch.Size([10, 10])


In [70]:
x = torch.randn(100, 3)
a = torch.tensor(
    [1, 2, 3.], requires_grad=True
)

y = torch.mv(x, a)
o = y.sum()

o.backward()
a.grad != x.sum(0)

tensor([True, True, True])

In [71]:
x.sum(0)

tensor([ 1.6881, -4.2507, -1.9916])

In [72]:
a.grad

tensor([ 1.6881, -4.2507, -1.9916])

In [73]:
o

tensor(-12.7882, grad_fn=<SumBackward0>)

In [75]:
y.shape

torch.Size([100])

In [78]:
(x.sum(0) * a).sum()

tensor(-12.7882, grad_fn=<SumBackward0>)

In [82]:
o.backward()
a.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [84]:
x = torch.randn(100, 3)
a = torch.tensor([1, 2, 3], requires_grad=True, dtype=torch.float)

In [85]:
y = torch.mv(x, a)
o = y.mean()
o.backward()

In [86]:
print('o:', o)
print('a.grad:', a.grad)

o: tensor(-0.0134, grad_fn=<MeanBackward0>)
a.grad: tensor([-0.1370,  0.0586,  0.0021])


In [92]:
(x.mean(0)*a).sum()

tensor(-0.0134, grad_fn=<SumBackward0>)